# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - helping-hands

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://helpinghands.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_4abdb4f8a20d44a9b97a8caa310e3257 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_44d213070db64c63945fbbd4e45c8b38 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.AzureAppService_ContainerUsername_4abdb4f8a20d44a9b97a8caa310e3257 }}/helpinghandserver:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'helping-hands'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b1b29b54b7ce4b9b88746f0edbc75a04 }}
        images: 'helpinghands.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4abdb4f8a20d44a9b97a8caa310e3257 }}/helpinghandserver:${{ github.sha }}'